# bfs graph traversal
gcc bfs_openmp.c -fopenmp -o bfs_omp

export OMP_NUM_THREADS=1
./bfs_omp

export OMP_NUM_THREADS=2
./bfs_omp

export OMP_NUM_THREADS=4
./bfs_omp

# dfs graph traversal
gcc dfs_openmp.c -fopenmp -o dfs_omp

export OMP_NUM_THREADS=1
./dfs_omp

export OMP_NUM_THREADS=2
./dfs_omp

export OMP_NUM_THREADS=4
./dfs_omp