#MPI BFS – Compile
mpicc bfs_mpi.c -o bfs_mpi

#Run with 1 process
mpirun -np 1 ./bfs_mpi

#Run with 2 processes
mpirun -np 2 ./bfs_mpi

#Run with 4 processes
mpirun -np 4 ./bfs_mpi


#MPI DFS – Compile
mpicc dfs_mpi.c -o dfs_mpi

#Run with 1 processes
mpirun -np 1 ./dfs_mpi

#Run with 2 processes
mpirun -np 2 ./dfs_mpi

#Run with 4 processes
mpirun -np 4 ./dfs_mpi